### ISSUE TITLE
SecurityError at line 3014

### ISSUE THREAD

**Issue by luis140219** [jmoenig/morphic.js#14]
![oopsies](https://cloud.githubusercontent.com/assets/8597264/6098526/36b39a98-afd9-11e4-9e8e-b9e3b9c96646.png)
When I move the mouse in my Starlings game, I get a SecurityError at line 3014 in morphic.js as of commit 28abbad.

Call stack:
Morph.prototype.isTransparentAt: morphic.js (3014, 9)
Anonymous function: morphic.js (9390, 9)
Array.prototype.forEach: [luismark.js](https://github.com/luis140219/luismark-javascript-library) (54, 9)
HandMorph.prototype.morphAtPointer: morphic.js (9389, 5)
HandMorph.prototype.processMouseMove: morphic.js (9665, 5)
Anonymous function: morphic.js (10292, 13)

luismark.js version: [here](https://github.com/luis140219/luismark-javascript-library/commit/3344424)

**Comment by cycomachead** [comment]
What browser are you using?

Also was this being run from a server or did you just load a file in the browser?

**Comment by jmoenig** [comment]
you're probably using a texture or image or svg that has a CORS issue, and / or running your application locally, i.e. not from a web server. Some image data ops only work (for whatever paranoid security reasons) if the web page is being supplied by a web-server and not locally.

**Comment by luis140219** [comment]
The server is luismark.github.io and the game is there. There was no CORS issue. The code is:
```javascript
data = ctx.getImageData(Math.floor(point.x),Math.floor(point.y),1,1);
```
The image is a black background and it isn't anywhere. It was set by CanvasRenderingContext2D.prototype.fillRect (native code method).
I actually runned my app locally.

**Comment by luis140219** [comment]
The game is online [on luismark's organisation GitHub Pages website](http://luismark.github.io/starlings/starlings.html). I'd like Jens to accept the invitation to join Luismark and start committing.

**Comment by luis140219** [comment]
I'm using Internet Explorer 11.0.9600.17501 (KB3008923).

**Comment by luis140219** [comment]
This no longer happens with 92b3b5d and #15.

**Comment by luis140219** [comment]
I will try to implement .isTransparentAt in StarlingsManagerMorph (the morph where the issue occurred).

**Comment by luis140219** [comment]
Jens can join [here](https://github.com/luismark) and commit [here](https://github.com/luismark/luismark.github.io/tree/master/starlings).

**Comment by jmoenig** [comment]
Thanks for the invitation, but I'm afraid I'm really too busy with my "real" job to help you debug your project. Also, please take into consideration that the issues you're running into might arise not out of *using* Morphic.js, but out of modding it :-)

**Comment by luis140219** [comment]
I've not modded Morphic.js. I've created a new module called "starlings" that is the game itself [here](https://github.com/luismark/luismark.github.io/tree/master/starlings). It contains 4 custom kinds of morphs:
- StarlingsManagerMorph* - the only direct child of the world and that carries out game actions (I call it the "manager" many times)
- StarlingsHeaderMorph* - the header at the top-left of the world.
- StarlingMorph - represents a Starling (like at the top of the issue description).
- BuildingMorph - represents a building on a planet.

asterisk: only used once

**Comment by luis140219** [comment]
Fixed in-app. I'll gonna close #14.

**Comment by luis140219** [comment]
This will affect other Morphic tools done by others. It's really important to merge #15.

**Comment by luis140219** [comment]
I have issues in my game: luismark/luismark.github.io#3, luismark/luismark.github.io#4 and luismark/luismark.github.io#7.

**Comment by jmoenig** [comment]
Again, this doesn't seem to be an issue of Morphic.js, but simply a browser canvas security model thing.

**Comment by luis140219** [comment]
The fixes should be done in a per-application basis. For the application, the background fix is the desired one.
