### ISSUE TITLE
improvement: high-dpi screens support (aka retina displays)

### ISSUE THREAD

**Issue by davidedc** [jmoenig/morphic.js#23]
While entry level devices (used for education) will most likely remain at "normal" dpi tiers, 50% of the "medium level" devices and all of the high-end devices (including most tablets) are moving to high-dpi screens.

https://github.com/davidedc/Zombie-Kernel/commit/42a7def011fd85660219d4426c14f99649854d27 and https://github.com/davidedc/Zombie-Kernel/commit/2c8bdfa791d53580dcab6622e64dd53c393df0af in Zombie Kernel provide support for high-dpi screens support (aka retina displays). Actual side-by-side screenshot of the difference below:

![screen shot 2015-02-17 at 20 32 39](https://cloud.githubusercontent.com/assets/769568/6236676/7c980d20-b6e4-11e4-846b-7853f4003f1b.png)

I'll likely have refactoring and optimisation in following commits, but the links above give the bulk of it. I tested on my test cases and it's OK. There is likely some excessive blitting and some of the "dormant" code I don't use has no adjustments...

**Comment by cycomachead** [comment]
Nice, I was working on this a bit.

How does the memory use compare?

**Comment by jmoenig** [comment]
Cool, Davide!! I've also researched into this, but then came across issues. It's *great* that you've pulled this off, I'm *very* interested in this!

**Comment by davidedc** [comment]
I didn't profile yet, I'd think memory usage is plain 4x (assuming here that canvas implementations doesn't work out some clever texture compression behind the scenes, which I highly doubt). morphic.js uses the backing store / retained windows technique for damage repair, that's memory heavy on its own... high-dpi  compounds on that I'm afraid... The good news is that high-dpi screens are _usually_ paired with matching higher-specs machines. But yes I'd expect some corner cases like running at full screen on big displays where buffers would get monstrous. Tablets could have a "small bus" problem there, I didn't try.

A "fix" I'd see to high memory usage is that all morphs that consist of a rectangle of flat colour, could repaint themselves issuing commands of the main canvas instead of retaining their own buffer and blitting it. For example the whole background "desktop" is a _big_ _extra_ FrameMorph buffer and it's a somewhat of a waste to keep such vast extent of memory for flat colour. It's an optimisation that would take some thinking cause the penMorph would still expect to paint on a dedicated buffer... and it would make the architecture uglier... and it only takes a year or so for all performance problems to go away etc. etc. It could be done reasonably easily though.

The way I did the migration:
* good news: all measures except the ones "very next" to the handling of buffer sizes remain exactly the same as before. So all things such as origin, bounds, widths, heights of morphs: stay the same, just now they represent "logical pixels" (or CSS pixels, if you will, since this is also how browsers handle the high-dpi shenanigans) instead of physical pixels.
* all canvas allocations need to be 2x on each dimension
* all drawing on said canvases needs to be done at scale 2x - so whenever there is a new canvas being created, as soon as the context is fetched from it - do a scale
* the points above take care of 90% of the changes and are relatively mechanical, the three below are more subtle.
* direct pixel accesses need some manual code tweaking (e.g. when transparency of a pixel is checked, when painting the color palette, when picking the color chosen in the palette)
* the blitting code in the damage repair phase needs some manual code tweaking
* code around text measurements I worked out manually too

**Comment by davidedc** [comment]
p.s. a draft demo is here: http://davidedc.github.io/Zombie-Kernel/buildhighdpi/worldWithSystemTestHarness.html

**Comment by davidedc** [comment]
p.p.s. note that only Chrome seems to work properly at the moment. Safari mangles most text. Firefox's rendering goes completely MIA.

**Comment by davidedc** [comment]
third commit of the series fixes Safari and Firefox: https://github.com/davidedc/Zombie-Kernel/commit/ac62b51409edbfa32fca301d4a4598002380db50 demo is again here: http://davidedc.github.io/Zombie-Kernel/buildhighdpi/worldWithSystemTestHarness.html

**Comment by davidedc** [comment]
this is now done by https://github.com/bl-nero https://github.com/jmoenig/morphic.js/commit/849d974b58dbdf83971939a0fc16df2be02c57b7
