### ISSUE TITLE
Complex morph duplication error

### ISSUE THREAD

**Issue by davidedc** [jmoenig/morphic.js#31]
Morph copying doesn't seem to work.

Steps:
1) open scroll morph
2) drag a text into it
3) open the inspector of the text and attach it to the scroll morph, so now the scrollmorph contains the text and its inspector
4) change a property of the text via the inspector, e.g. alpha
5) duplicate the whole scrollmorph

expected: the new scroll morph has its own textmorph and its own inspector. The new inspector should be hooked to the new textmoprh, and it's possible to change the transparency similarly to what was done within the first scrollMorph.

result: the new inspector is not linked to the new textmorph, we can't change the opacity as we did within the first scrollmorph.

![screen shot 2015-06-25 at 16 05 19](https://cloud.githubusercontent.com/assets/769568/8357771/879046e6-1b54-11e5-8605-bbcfe485427a.png)

**Comment by davidedc** [comment]
see also https://github.com/jmoenig/morphic.js/issues/16

**Comment by jmoenig** [comment]
Thanks, Davide! I was afraid someting like this would come up :-(

**Comment by jmoenig** [comment]
I think instead of getting rid of all those special cased `SomeMorph::copyRecordingReferences()` methods we should probably have moved their functionality into special cased `SomeMorph::updateReferences`method.

**Comment by jmoenig** [comment]
Okay, so maybe it's *just* about inspectors? This could be an easy fix...

**Comment by davidedc** [comment]
I quickly threw some non-trivial cases of complex morphs with targeting at it and it seems fine. I think this might be only about the inspectors. Unless inspectors are exercising some more general mechanism that could be escaping me, not sure. (I'd volunteer but I'd need a half-day on this and I'd come from the angle of checking how I tackled this in Zombie Kernel which is quite different since I do via serialisation)...

**Comment by jmoenig** [comment]
Naw, I got it, thanks! I'm going to push a little fix for this later today. Thanks a lot for the quick and thorough test!
