### ISSUE TITLE
Incorrect TextMorph.prototype.slotAt when short line

### ISSUE THREAD

**Issue by brollb** [jmoenig/morphic.js#51]
When there is a TextMorph with a short line (such as the final line in "import a picture from another web page or from a file on your computer by dropping it here" in Snap!), `slotAt` can return an invalid column.

[Here](https://github.com/jmoenig/morphic.js/blob/master/morphic.js#L9633-L9636) is the problematic code. This error is not obvious as `context.measureText(undefined) === context.measureText("undefined")`. That is, `measureText` appears to cast undefined input to a string. 

This is problematic after adding the [URL detection](https://github.com/jmoenig/morphic.js/blob/master/morphic.js#L1326) as the character (fetched using the slot from `slotAt`) is undefined and has no `.match` function. Of course, this would be problematic for any other (regex) character detection relying on `slotAt` for the character such as https://github.com/jmoenig/morphic.js/blob/master/morphic.js#L1322

**Comment by jmoenig** [comment]
Thanks!
