### ISSUE TITLE
"Unclosable" MenuMorphs

### ISSUE THREAD

**Issue by brollb** [jmoenig/morphic.js#55]
After customizing some of the menus in NetsBlox, I noticed that menus can sometimes be unable to be closed on background click. It seems the issue is related to an already closed MenuMorph being destroyed more than once. 

In my specific case, the `showMessage` method in the IDE_Morph is calling `destroy` on the menu regardless of the fact that it has already been destroyed (and there is a different active menu already). Since the [MenuMorph assumes it is the activeMenu](https://github.com/jmoenig/morphic.js/blob/master/morphic.js#L8404), this results in `world.activeMenu` being set to null and the actual active menu is no longer closed on background click.

This could be addressed a couple different ways but it seems safe to say that a menu should not be clearing `world.activeMenu` unless it is the current active menu.

Steps to reproduce:
- Display a MenuMorph
- Display a new MenuMorph
- Call `destroy()` on the first MenuMorph

**Comment by jmoenig** [comment]
Hi Brian, yes! This bug has been haunting me for a while now. I *thought* I had it covered some time ago, and it hasn't come up for me recently. I dimly remember fixing something. Let me try to found out what exactly. Maybe it was something in Snap. It's great that you're investigating this, thank you!

**Comment by jmoenig** [comment]
Ah, found it! It used to be that sometimes moving out of submenus left the main menu open. So I had to reassign the main menu to again the world's `activeMenu` to make sure it got closed when the next menu pops up: https://github.com/jmoenig/morphic.js/commit/bdf9cc9f50a4dea9ce20f911fd542779301c584d

So, I guess the larger point is to make sure that menus are always ever opened by a function that bottoms out at `MenuMorph >> popUp()` https://github.com/jmoenig/morphic.js/blob/c06b12b244aa34de6c8c259b5ab0294bcab10c2f/morphic.js#L8176

Can you tell me more about the cases in which you run into orphaned menus? It seems to me that not closing them if they're not active only addresses part of the issue, but I'm not sure.

Thanks!

**Comment by brollb** [comment]
My understanding is that the timer in `showMessage` can result in a menu being destroyed twice ([here](https://github.com/jmoenig/Snap/blob/master/src/gui.js#L6377-L6385)) where the second time clears `world.activeMenu` without destroying the menu so it becomes unclosable. A bit more involved explanation is below :)

In my specific case, the problem was that a menu was opened while a message was shown (w/ a timer to destroy it). The problem seems to be that when `showMessage(someMessage, secs)` is called, it pops up the menu using `popUpCenteredInWorld`. If another menu (such as the cloud menu) is opened during this time, the current message/active menu will be destroyed and the new menu will be the active one. The problem now arises when the timer goes off and destroys the first message as this will set `activeMenu` (which is the cloud menu) to null. The cloud menu will now be unclosable since the reference to it (`activeMenu`) was cleared without destroying the menu.

**Comment by brollb** [comment]
It seems fair to think that `destroy()` should be idempotent so I decided to add the check when setting `activeMenu` but it also would work to make sure that `destroy()` isn't ever called twice.

**Comment by jmoenig** [comment]
A classic race condition with `showMessage`, of course! Thanks, that clears it up for me. Great, that you've found and fixed this!
