### ISSUE TITLE
popUpCenteredInWorld does not center menu

### ISSUE THREAD

**Issue by brollb** [jmoenig/morphic.js#57]
When calling `popUpCenteredInWorld`, the menu is centered using the pre-rendered size (the actual size isn't computed until `this.createItems()` is called in `popup`). This isn't noticeable for small menus but becomes obvious when the menu is large:
![DeepinScreenshot_chromium_20210630101857](https://user-images.githubusercontent.com/4982789/124135422-6b253380-da49-11eb-9954-fb2480f18e8c.png)

**Comment by brollb** [comment]
Originally discovered here: https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/issues/1255

**Comment by jmoenig** [comment]
Wow, how did I not ever notice this glaringly obvious bug ever before? Thank you so much!

**Comment by brollb** [comment]
No problem! Happy to help :)
